"""
rexdr - Launcher
config_writer.py - Configuration file writer

Author  : Rayyan Umair
Date    : 2026-06-21
Purpose : Writes .env, targets.yaml, and zones.yaml from the launcher's
          configuration wizard input. Validates required fields before
          writing. This is the only module that writes REXDR's runtime
          configuration files - the wizard UI calls into here, nothing
          writes these files directly.
Contact : rayyanxumair@gmail.com
GitHub  : github.com/rayyan-umair/rexdr

"The foundation everything else is built on."

--- Part of the REXDR platform. ---
"""

# -- Standard Library --------------------------------------------------------
import logging
from pathlib import Path

# -- Third Party -------------------------------------------------------------
import yaml

# ============================================================================

logger = logging.getLogger(__name__)


class ConfigWriter:
    """
    Writes REXDR's runtime configuration files from launcher wizard input.
    All paths are relative to the REXDR repo root passed in at construction.
    """

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = repo_root
        self.env_path = repo_root / ".env"
        self.targets_path = repo_root / "config" / "targets.yaml"
        self.zones_path = repo_root / "config" / "zones.yaml"

    # -------------------------------------------------------------------------
    # .env writer
    # -------------------------------------------------------------------------

    def write_env(self, values: dict) -> None:
        """
        Write the .env file from a dict of key-value pairs collected
        by the wizard. Required keys are validated before writing -
        missing required values raise ValueError rather than writing
        a broken config silently.
        """
        required = ["WINRM_USERNAME", "WINRM_PASSWORD", "LDAP_BASE_DN", "LDAP_DOMAIN"]
        missing = [k for k in required if not values.get(k)]

        if missing:
            raise ValueError(
                f"Missing required configuration values: {', '.join(missing)}"
            )

        lines = [
            "# =============================================================================",
            "# REXDR - Environment Configuration",
            "# Generated by the REXDR launcher. Do not commit this file.",
            "# =============================================================================",
            "",
            "# -- Windows / Active Directory credentials ----------------------------------",
            f"WINRM_USERNAME={values.get('WINRM_USERNAME', '')}",
            f"WINRM_PASSWORD={values.get('WINRM_PASSWORD', '')}",
            f"LDAP_BASE_DN={values.get('LDAP_BASE_DN', '')}",
            f"LDAP_DOMAIN={values.get('LDAP_DOMAIN', '')}",
            "",
            "# -- Network capture -----------------------------------------------------------",
            f"CAPTURE_INTERFACE={values.get('CAPTURE_INTERFACE', 'eth0')}",
            "",
            "# -- AI integration --------------------------------------------------------------",
            f"AI_PROVIDER={values.get('AI_PROVIDER', '')}",
            f"AI_API_KEY={values.get('AI_API_KEY', '')}",
            f"AI_MODEL={values.get('AI_MODEL', '')}",
            f"AI_BASE_URL={values.get('AI_BASE_URL', '')}",
            "",
            "# -- Vulnerability intelligence ---------------------------------------------------",
            f"NVD_API_KEY={values.get('NVD_API_KEY', '')}",
            "",
            "# -- Platform settings -----------------------------------------------------------",
            f"DB_RETENTION_DAYS={values.get('DB_RETENTION_DAYS', '30')}",
            f"SCAN_INTERVAL_MINUTES={values.get('SCAN_INTERVAL_MINUTES', '60')}",
            f"CVE_SYNC_INTERVAL_HOURS={values.get('CVE_SYNC_INTERVAL_HOURS', '24')}",
            "",
        ]

        self.env_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(".env written - path=%s", self.env_path)

    def read_env(self) -> dict:
        """
        Read the existing .env file back into a dict, if it exists.
        Used to pre-populate the wizard on subsequent launches so the
        user is not forced to re-enter everything every time.
        """
        if not self.env_path.exists():
            return {}

        values = {}
        for line in self.env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()

        return values

    # -------------------------------------------------------------------------
    # targets.yaml writer
    # -------------------------------------------------------------------------

    def write_targets(self, targets: list[dict]) -> None:
        """
        Write config/targets.yaml from a list of target dicts collected
        by the targets editor. Each target dict must have at minimum
        name, ip, and priority - validated before writing.
        """
        for t in targets:
            missing = [k for k in ("name", "ip", "priority") if not t.get(k)]
            if missing:
                raise ValueError(
                    f"Target '{t.get('name', 'unnamed')}' missing required fields: {', '.join(missing)}"
                )

        self.targets_path.parent.mkdir(parents=True, exist_ok=True)

        data = {"targets": targets}

        header = (
            "# =============================================================================\n"
            "# REXDR - Target Configuration\n"
            "# Generated by the REXDR launcher targets editor.\n"
            "# =============================================================================\n\n"
        )

        with open(self.targets_path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)

        logger.info("targets.yaml written - path=%s count=%d", self.targets_path, len(targets))

    def read_targets(self) -> list[dict]:
        """Read the existing targets.yaml back into a list of dicts."""
        if not self.targets_path.exists():
            return []

        with open(self.targets_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        return data.get("targets", [])

    # -------------------------------------------------------------------------
    # zones.yaml writer
    # -------------------------------------------------------------------------

    def write_zones(self, zones: list[dict]) -> None:
        """
        Write config/zones.yaml from a list of zone dicts collected by
        the wizard. Each zone must have zone_id, display_name, and cidr.
        """
        for z in zones:
            missing = [k for k in ("zone_id", "display_name", "cidr") if not z.get(k)]
            if missing:
                raise ValueError(
                    f"Zone '{z.get('zone_id', 'unnamed')}' missing required fields: {', '.join(missing)}"
                )

        self.zones_path.parent.mkdir(parents=True, exist_ok=True)

        data = {"zones": zones}

        header = (
            "# =============================================================================\n"
            "# REXDR - Network Zone Configuration\n"
            "# Generated by the REXDR launcher.\n"
            "# =============================================================================\n\n"
        )

        with open(self.zones_path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)

        logger.info("zones.yaml written - path=%s count=%d", self.zones_path, len(zones))

    def read_zones(self) -> list[dict]:
        """Read the existing zones.yaml back into a list of dicts."""
        if not self.zones_path.exists():
            return []

        with open(self.zones_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        return data.get("zones", [])